spring:
  application:
    name: jmspoc
  jms:
    listener:
      max-concurrency: 256
      receive-timeout: 60000 # in ms!!!
      concurrency: 256
    cache:
      session-cache-size: 1024
      consumers: true
      producers: true
      enabled: true



  jmx:
    enabled: false


management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus

ibm:
  mq:
    queueManager: QM1
    channel: DEV.ADMIN.SVRCONN
    connName: localhost(1414)
    user: admin
    password: passw0rd
    pool:
      enabled: true
      max-connections: 4
      max-sessions-per-connection: 500



logging:
  level:
    com:
      ibm:
        mq:
          spring:
            boot: WARN
    org:
      springframework:
        jms: WARN